### ISSUE TITLE
wrong csi command in documentation mentioning chicken-home and locate-repository?

### ISSUE THREAD

**Issue by marcomaggi** [ursetto/chicken-doc#2]
The documentation at [http://wiki.call-cc.org/eggref/5/chicken-doc](url) shows:

```
$ cd `csi -p '(chicken-home)'`
```

but with Chicken 5.0.0:

```
$ csi -p '(chicken-home)'

Error: unbound variable: chicken-home

	Call history:

	<syntax>	  (##core#begin (##core#require library scheme#) (##core#require library chicken.base#) (##core#requir...
	<syntax>	  (##core#require library scheme#)
	<syntax>	  (##sys#load-library (##core#quote library))
	<syntax>	  (##core#quote library)
	<syntax>	  (##core#require library chicken.base#)
	<syntax>	  (##sys#load-library (##core#quote library))
	<syntax>	  (##core#quote library)
	<syntax>	  (##core#begin (##core#require expand chicken.syntax#))
	<syntax>	  (##core#require expand chicken.syntax#)
	<syntax>	  (##sys#load-library (##core#quote expand))
	<syntax>	  (##core#quote expand)
	<eval>	  (##sys#load-library (##core#quote library))
	<eval>	  (##sys#load-library (##core#quote library))
	<eval>	  (##sys#load-library (##core#quote expand))
	<syntax>	  (chicken-home)
	<eval>	  (chicken-home)	<--
```

The syntactic binding `locate-repository` is also unbound.

**Comment by ursetto** [comment]
locate-repository is bound if you import chicken-doc as specified in the docs. (Paste your exact commands here if you are still having problems)

    $ ~/local/chicken/5.0.0/bin/csi -R chicken-doc -p "(locate-repository)"
    /home/jim/local/chicken/5.0.0/share/chicken/chicken-doc

chicken-home requires chicken.platform on C5.

    $ ~/local/chicken/5.0.0/bin/csi -R chicken.platform -p '(chicken-home)'
    /home/jim/local/chicken/5.0.0/share/chicken

Let me update the docs for that and also point to the v5 tarball.

**Comment by ursetto** [comment]
Completed. Let me know if ok

**Comment by marcomaggi** [comment]
Everything worked, thanks!
