### ISSUE TITLE
is there a special reason for http://api.call-cc.org does not look up the document of function like call-with-port in Scheme base

### ISSUE THREAD

**Issue by APIPLM** [ursetto/chicken-doc#8]
As I was looking for the document of function `call-with-port` in the [API document for chicken](http://api.call-cc.org), but I got the below response in the result page.
`No node found matching identifier call-with-port`

Seem like API document for chicken document does not have the index for this symbol, when come to the REPL to check the function `call-with-port` after running `(import (scheme base))`, it is there. my question is that is there a special reason for http://api.call-cc.org does not index the symbol `call-with-port` , which is in the scheme base. Thank in advanced.

**Comment by ursetto** [comment]
It seems to me that you may be using the r7rs egg, as call-with-port is not defined in base Chicken.

The documentation at api.call-cc.org is built from the upstream Chicken documentation (which you can see at wiki.call-cc.org), so it would have to be defined there. 

Unfortunately these identifiers are not documented upstream (as you can see at https://wiki.call-cc.org/eggref/5/r7rs), so they are not documented at api.call-cc.org.

I would suggest posting a request to the chicken-users mailing list, and requesting that the r7rs identifiers be imported into the documentation. Probably, no one has had time.
